// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omglnkwppbzviojlnlxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tZ2xua3dwcGJ6dmlvamxubHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzEwNzcsImV4cCI6MjA2OTM0NzA3N30.f4bQp1rK1lmBbOOf8y4SH1aGPw02ih4vNxpNEPOe2zQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create the base Supabase client
const baseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Export the base client for now - debug wrapper will be applied in App.tsx
export const supabase = baseClient;